[workspace]
members = [
    "contrail_types",
    "core_daemon", "dashboard", "importer",
    "scrapers", "tools/exporter", "tools/wrapup", "analysis",
    "tools/memex", "tools/contrail",
    "contrails",
]
resolver = "2"
