[package]
name = "core_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
scrapers = { path = "../scrapers" }
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify-rust = "4.11.0"
dirs = "5.0.1"
