[package]
name = "importer"
version = "0.1.0"
edition = "2024"

[dependencies]
scrapers = { path = "../scrapers" }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
